# =====================================================================
# name: docker-compose.yml
# description: base docker-compose file defining services and volumes
# =====================================================================

x-common-labels: &common-labels
  labels:
    project.name: "Matcha"
    project.description: "A dating application, built with modern web technologies."

services:
  proxy:
    <<: *common-labels
    build:
      context: ./services/proxy
      dockerfile: Dockerfile
    container_name: matcha_proxy
    volumes:
      - nginx_certs:/etc/nginx/certs
    restart: unless-stopped

  frontend:
    <<: *common-labels
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: matcha_frontend

  backend:
    <<: *common-labels
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    container_name: matcha_backend

  database:
    <<: *common-labels
    build:
      context: ./services/database
      dockerfile: Dockerfile
    container_name: matcha_database
    volumes:
      - db_data:/var/lib/postgresql/data

# ==========================================================
# volumes definition for the services
# ==========================================================
volumes:
  nginx_certs:
    <<: *common-labels
    name: matcha_nginx_certs_volume
    driver: local

  db_data:
    <<: *common-labels
    name: matcha_postgres_volume
    driver: local
