# ==========================================================
#
#
# ==========================================================

# x-common-args: &common-args
#   VERSION: ${VERSION:-latest}
#   BUILD_DATE: ${BUILD_DATE:-unknown}
#   REVISION: ${REVISION:-unknown}

services:
  # ==========================================================
  #
  # ==========================================================
  proxy:
    build:
      target: production
      context: ./services/proxy
      dockerfile: Dockerfile
    env_file:
      - ./services/proxy/.env.prod
    ports:
      - "80:80"
      - "443:443"

  # ==========================================================
  #
  # ==========================================================
  frontend:
    build:
      target: production
      context: ./services/frontend
      dockerfile: Dockerfile
    image: matcha_frontend_image:${VERSION:-latest}-prod
    env_file:
      - ./services/frontend/.env.prod

  # ==========================================================
  #
  # ==========================================================
  backend:
    build:
      target: production
      context: ./services/backend
      dockerfile: Dockerfile
    image: matcha_backend_image:${VERSION:-latest}-prod
    env_file:
      - ./services/backend/.env.prod

  # ==========================================================
  #
  # ==========================================================
  database:
    env_file:
      - ./services/database/.env.prod
