

upstream  {
    frontend {
        server matcha_frontend:80;
    }
}

upstream  {
    backend {
        server matcha_backend:8000;
    }
}


server {
    listen 80;
    server_name  _;

    return 301 https://$host$request_uri;
}


server {
    listen 443 ssl;
    server_name  _;


    ssl_certificate file;
    ssl_certificate_key file;



    location / {

    }

    location / {


   }

    location = /media/ {
        internal;
        alias /usr/share/nginx/html/media/;
    }
}
